dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

dist: xenial

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157

install:
  - npm install
  - npm install -g tslint
  - npm install -g typescript@next

script:
  - npm run test -- --no-watch --no-progress
  - npm run build

deploy:
  # beta testing
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./dist/takemeto
    on:
      branch: develop
    # production
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: takeme-2019
    on:
      branch: master